AreaAtuacao:
    type: entity
    table: area_atuacao
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
