Curso:
    type: entity
    table: curso
    indexes:
        fk_curso_modalidade1_idx:
            columns:
                - modalidade_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        grau:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
    manyToOne:
        modalidade:
            targetEntity: Modalidade
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                modalidade_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
