Pessoa:
    type: entity
    table: pessoa
    indexes:
        fk_pessoa_endereco1_idx:
            columns:
                - endereco_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        rg:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        cpf:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        dataNascimento:
            type: datetime
            nullable: false
            comment: ''
            column: data_nascimento
        formacao:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
    manyToOne:
        endereco:
            targetEntity: Endereco
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                endereco_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        empresa:
            targetEntity: Empresa
            cascade: {  }
            mappedBy: pessoa
            inversedBy: null
            joinTable: null
            orderBy: null
        contato:
            targetEntity: Contato
            cascade: {  }
            mappedBy: null
            inversedBy: pessoa
            joinTable:
                name: pessoa_has_contato
                joinColumns:
                    -
                        name: pessoa_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: contato_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
